apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
data:
  MCP_SERVER_PORT: {{ .Values.config.MCP_SERVER_PORT | quote }}
  CORS_ORIGINS: {{ .Values.config.CORS_ORIGINS | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.config.NEXT_PUBLIC_API_URL | quote }}